name: Java CI with Gradle

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.0
      with:
        java-version: 21
        distribution: 'zulu'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Remove *-dev.jar
      run: rm ./build/libs/*-dev.jar || true

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: dist/

    - name: Archive mapping.txt
      uses: actions/upload-artifact@v3
      with:
        name: Mappings
        path: build/tmp/proguard/mapping.txt

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-1.21.5"
        prerelease: false
        title: "NEW 1.21.5 Build"
        files: |
          ./build/libs/*.jar
